# 项目相关配置
rabbit:
  #文件映射路径
  profile: /profile
  jmeterfile: /profile/jmeter
  uifile: /profile/UI
  appfile: /profile/app
  systemfile: /profile/system
  reportEmailDoman:
server:
  port: 8889
  servlet:
    context-path: /public
# 解决Tomcat问题
  tomcat:
    max-http-header-size: 10240000
    max-http-post-size: 10240000
#  tomcat:
#    accesslog:
#      buffered: true
#      directory: D:/logs
#      enabled: true
#      file-date-format: .yyyy-MM-dd
#      pattern: common
#      prefix: access_log
#      rename-on-rotate: false
#      request-attributes-enabled: false
#      rotate: true
#      suffix: .log
spring:
#  profiles:
#    active: dev
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      #druid相关配置
      druid:
        #监控统计拦截的filters
        filters: stat
        driver-class-name: com.mysql.jdbc.Driver
        #基本属性
        url: jdbc:mysql://118.89.90.148:3307/rabbit-v2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        #配置初始化大小/最小/最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        stat-view-servlet:
          enabled: true
          url-pattern: /monitor/druid/*
#          login-username: admin
#          login-password: admin
  #    格式化日期
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #启动时加载
  mvc:
    servlet:
      load-on-startup: 0
  # 上传文件限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  redis配置
  redis:
    database: 0 #redis数据库索引，默认为0
    host: 118.89.90.148
    port: 6379
#    password:
    timeout: 10s #连接超时时间（毫秒）
    jedis:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 244776919@qq.com  #smtp邮箱地址，不是你自己的邮箱，如何申请请百度
    password: xuzrqkazsiifbgcf
    protocol: smtp
    test-connection: false
#  boot:
#    admin:
#      context-path: springboot-admin
#      notify:
#        mail:
#          enabled: false
#    properties:
#      mail.smtp.auth: true
##showSql
#logging:
#  level:
#    com:
#      rabbit:
#        dao : debug

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-aliases-package: com.rabbit.model  # 注意：对应实体类的路径
    #开启驼峰转换
  configuration:
    mapUnderscoreToCamelCase: true

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
swagger:
  enable: true #是否禁用swagger
#token过期时间设置
token:
  expire:
    seconds: 86400 # token过期时间，24个小时
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)

logging:
  config: classpath:logback-admin.xml
log:
  level:
#日志级别从低到高分为：
#  配置TRACE < DEBUG < INFO < WARN < ERROR < FATAL
    root: INFO
    my: DEBUG
  file: logs/admin-server.log
  maxsize: 10MB